
site:
  about:
    siteName: Trellis
    siteDescription: A Kotlin implementation of the Specification Pattern

theme:
  social:
    other:
      - link: '/'
        label: 'Home'
        icon: 'fas fa-home'
      - link: 'https://github.com/copper-leaf/trellis'
        label: 'Github'
        icon: 'fab fa-github'
      - link: 'https://twitter.com/OrchidSSG'
        label: 'Twitter'
        icon: 'fab fa-twitter'
  menu:
  - type: 'page'
    title: 'Home'
    itemId: 'Home'
  - type: 'wikiSections'
  - type: 'page'
    itemId: 'Changelog'
  sidebarBackground: 'primary'
  sidebarBackgroundType: GRADIENT
  colors:
    purple: '#8CC4A5'
    blue: '#449999'
  useSidebarSearch: true

services:
  publications:
    stages:
      - type: ghPages
        branch: gh-pages
        latestDirName: latest
        publishType: CleanBranch
        username: copper-leaf
        repo: trellis
      - type: githubReleases
        repo: copper-leaf/trellis

allPages:
  components:
    - type: "pageContent"
    - type: "prism"
      githubTheme: 'duotone-light'
      languages:
        - kotlin
        - java
        - groovy
  extraCss:
    - 'inline:all.scss:
      code.language-kotlin .token.number { margin: 0; padding: 0; background: none; border: none; font-size: 1em; min-width: 0; }
      code.language-kotlin .token.operator { margin: 0; padding: 0; background: none; border: none; font-size: 1em; min-width: 0; }
      .content blockquote, .content pre { border-left: 5px solid #8CC4A5; }
      .content code { color: #8CC4A5; }
      .content code[class*="language-"], .content pre[class*="language-"] { color: #8CC4A5; font-size: 0.875em; }
      '