
site:
  about:
    siteName: Trellis
    siteDescription: A Kotlin implementation of the Specification Pattern

theme:
  social:
    github: 'copper-leaf/trellis'
  primaryColor: '#449999'
  bannerColor: '#449999'
  menu:
  - type: 'link'
    title: 'Home'
    url: '#{$0|baseUrl}/'
  - type: 'link'
    title: 'Api Docs'
    url: '#{$0|baseUrl}/api'
  trianglifyOptions:
    x_colors: ['#88ffe0', '#000000', '#88ffe0']
  useSidebarSearch: true

pages:
  staticPages:
    extraCss:
      - 'assets/dokka/style.scss'

services:
  publications:
    stages:
      ghPages:
        branch: gh-pages
        latestDirName: latest
        publishType: CleanBranch
        username: copper-leaf
        repo: trellis
